spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

  jpa:
    show-sql: false

app:
  jwt:
    secret: ${JWT_SECRET}

logging:
  level:
    com.medical.demo: INFO
    org.springframework.security: WARN
